-- MySQL Script generated by MySQL Workbench
-- 11/13/16 12:37:15
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema reserva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reserva` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `reserva` ;

-- -----------------------------------------------------
-- Table `reserva`.`c_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`c_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `cmpcorreo` VARCHAR(30) NULL,
  `cmpcontrasena` VARCHAR(15) NULL,
  `cmpnombre` VARCHAR(25) NULL,
  `cmpapellidoPaterno` VARCHAR(25) NULL,
  `cmpapellidoMaterno` VARCHAR(25) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`c_estadoReservacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`c_estadoReservacion` (
  `id_estadoReservacion` INT NOT NULL,
  `estado` VARCHAR(12) NULL,
  PRIMARY KEY (`id_estadoReservacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`p_reservacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`p_reservacion` (
  `id_reservacion` VARCHAR(45) NOT NULL,
  `cmpfechaEntrada` DATE NULL,
  `cmpfechaSalida` DATE NULL,
  `cmpnumeroDeActividades` INT NULL,
  `cmpcantidadPersonas` INT NULL,
  `cmpcomprobantePago` VARCHAR(45) NULL,
  `id_usuario` INT NOT NULL,
  `id_estadoReservacion` INT NOT NULL,
  PRIMARY KEY (`id_reservacion`),
  INDEX `p_reservacion_fki01` (`id_usuario` ASC),
  INDEX `p_reservacion_fki02` (`id_estadoReservacion` ASC),
  CONSTRAINT `p_reservacion_fk01`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `reserva`.`c_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `p_reservacion_fk02`
    FOREIGN KEY (`id_estadoReservacion`)
    REFERENCES `reserva`.`c_estadoReservacion` (`id_estadoReservacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`c_paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`c_paquete` (
  `id_paquete` INT NOT NULL AUTO_INCREMENT,
  `cmpnombrePaquete` VARCHAR(25) NULL,
  `cmptarifa` DOUBLE NULL,
  `cmpdetalle` VARCHAR(100) NULL,
  `cmpurl` VARCHAR(45) NULL,
  PRIMARY KEY (`id_paquete`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`c_cabania`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`c_cabania` (
  `id_cabania` INT NOT NULL AUTO_INCREMENT,
  `cmpnombre` VARCHAR(25) NULL,
  `cmptarifa` DOUBLE NULL,
  `cmpdescripcion` VARCHAR(100) NULL,
  `cmpurl` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cabania`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`c_actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`c_actividad` (
  `id_actividad` INT NOT NULL AUTO_INCREMENT,
  `cmpnombreActividad` VARCHAR(25) NULL,
  `cmptarifa` DOUBLE NULL,
  `cmpdetalle` VARCHAR(100) NULL,
  `cmpurl` VARCHAR(45) NULL,
  PRIMARY KEY (`id_actividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`c_turista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`c_turista` (
  `id_usuario` INT NOT NULL,
  `cmpnumeroTelefono` VARCHAR(15) NULL,
  `cmplugarOrigen` VARCHAR(45) NULL,
  `cmpfechaNacimiento` DATE NULL,
  INDEX `c_turista_fki01` (`id_usuario` ASC),
  CONSTRAINT `c_turista_fk01`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `reserva`.`c_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`c_asignacionPaquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`c_asignacionPaquete` (
  `id_reservacion` VARCHAR(45) NOT NULL,
  `id_actividad` INT NOT NULL,
  PRIMARY KEY (`id_reservacion`, `id_actividad`),
  INDEX `c_asignacionPaquete_fki01` (`id_actividad` ASC),
  INDEX `c_asignacionPaquete_fki02` (`id_reservacion` ASC),
  CONSTRAINT `c_asignacionPaquete_fk01`
    FOREIGN KEY (`id_reservacion`)
    REFERENCES `reserva`.`p_reservacion` (`id_reservacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `c_asignacionPaquete_fk02`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `reserva`.`c_actividad` (`id_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`c_asignacionCabania`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`c_asignacionCabania` (
  `id_reservacion` VARCHAR(45) NOT NULL,
  `id_cabania` INT NOT NULL,
  PRIMARY KEY (`id_reservacion`, `id_cabania`),
  INDEX `c_asignacionCabania_fki01` (`id_cabania` ASC),
  INDEX `c_asignacionCabania_fki02` (`id_reservacion` ASC),
  CONSTRAINT `c_asignacionCabania_fk01`
    FOREIGN KEY (`id_reservacion`)
    REFERENCES `reserva`.`p_reservacion` (`id_reservacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `c_asignacionCabania_fk02`
    FOREIGN KEY (`id_cabania`)
    REFERENCES `reserva`.`c_cabania` (`id_cabania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`c_asignacionPaqueteActividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`c_asignacionPaqueteActividad` (
  `id_paquete` INT NOT NULL,
  `id_actividad` INT NOT NULL,
  PRIMARY KEY (`id_paquete`, `id_actividad`),
  INDEX `c_asignacionPaqueteActividad_fki01` (`id_actividad` ASC),
  INDEX `c_asignacionPaqueteActividad_fki02` (`id_paquete` ASC),
  CONSTRAINT `c_asignacionPaqueteActividad_fk01`
    FOREIGN KEY (`id_paquete`)
    REFERENCES `reserva`.`c_paquete` (`id_paquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `c_asignacionPaqueteActividad_fk02`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `reserva`.`c_actividad` (`id_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`c_asignacionPaquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`c_asignacionPaquete` (
  `id_reservacion` VARCHAR(45) NOT NULL,
  `id_actividad` INT NOT NULL,
  PRIMARY KEY (`id_reservacion`, `id_actividad`),
  INDEX `c_asignacionPaquete_fki01` (`id_actividad` ASC),
  INDEX `c_asignacionPaquete_fki02` (`id_reservacion` ASC),
  CONSTRAINT `c_asignacionPaquete_fk01`
    FOREIGN KEY (`id_reservacion`)
    REFERENCES `reserva`.`p_reservacion` (`id_reservacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `c_asignacionPaquete_fk02`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `reserva`.`c_actividad` (`id_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
